---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@3.0.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          - debian-10
          - debian-11
          - ubuntu-1804
          - ubuntu-2004
        suite:
          - disable
          - add
          - remove
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: test-kitchen
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
          set -x
          sudo journalctl -l --since today
          KITCHEN_LOCAL_YAML=kitchen.dokken.yml /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"
